# Generated by Django 2.2.6 on 2019-11-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quotes',
            new_name='stock',
        ),
    ]
